#!/bin/bash
#SBATCH -p csgpus
###SBATCH --gres=gpu:H100:2
#SBATCH --gres=gpu:1
#SBATCH --nodelist=racc2-gpu-2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --mem=400G
#SBATCH --time=15-0:00:00
### #SBATCH --time=2:00:00
#SBATCH --job-name=CMMLoc_MNCLv4
#SBATCH --output=/share/nas/cs-nas/zh932237/CMMLoc_MNCLv4/logs/%x-%j.out
#SBATCH --error=/share/nas/cs-nas/zh932237/CMMLoc_MNCLv4/logs/%x-%j.err

# ---- Force ALL caches to node-local (avoid /home and /share/nas quotas) ----
CACHE_BASE=/share/nas/cs-nas/zh932237/hf_cache
mkdir -p "$CACHE_BASE"/{hf,hub,transformers,torch,xdg,tmp,pip}

export HF_HOME="$CACHE_BASE/hf"
export HF_HUB_CACHE="$CACHE_BASE/hub"
export TRANSFORMERS_CACHE="$CACHE_BASE/transformers"
export TORCH_HOME="$CACHE_BASE/torch"
export XDG_CACHE_HOME="$CACHE_BASE/xdg"
export TMPDIR="$CACHE_BASE/tmp"
export PIP_CACHE_DIR="$CACHE_BASE/pip"

# Show what will be used (very important for debugging)
echo "HF_HOME=$HF_HOME"
echo "HF_HUB_CACHE=$HF_HUB_CACHE"
echo "TRANSFORMERS_CACHE=$TRANSFORMERS_CACHE"
echo "XDG_CACHE_HOME=$XDG_CACHE_HOME"
# -------------------------------------------------------------------------





set -euo pipefail

cd /share/nas/cs-nas/zh932237/CMMLoc_MNCLv4
mkdir -p logs

# Activate your env (optional for hostname, but fine to keep)
source  /share/nas/cs-nas/zh932237/env_cmmloc_mnclv4/bin/activate

# Optional: show GPUs allocated
echo "Host: $(hostname)"
nvidia-smi -L

# Your requested command:
hostname

python -m training.coarse --batch_size 64 --coarse_embed_dim 256 --shuffle --base_path ./data/k360_30-10_scG_pd10_pc4_spY_all --use_features class color position num --no_pc_augment --fixed_embedding --epochs 20 --learning_rate 0.0005 --lr_scheduler step --lr_step 5 --lr_gamma 0.4 --temperature 0.1 --ranking_loss contrastive --hungging_model t5-large --text_max_length 128 --lambda_mncl 0.0 --mncl_proj_dim 256 --use_trainable_reranker --lambda_reranker 0.3 --trainable_rerank_topn 50 --skip_train_eval --cpus 0 --pointnet_path ./checkpoints/pointnet_acc0.86_lr1_p256.pth --folder_name coarsev6_batch64_epoch20
