#!/bin/bash
#SBATCH -p csgpus
###SBATCH --gres=gpu:H100:2
#SBATCH --gres=gpu:1
#SBATCH --nodelist=racc2-gpu-3
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --mem=400G
#SBATCH --time=15-0:00:00
### #SBATCH --time=2:00:00
#SBATCH --job-name=CMMLoc_MNCLv4
#SBATCH --output=/share/nas/cs-nas/zh932237/CMMLoc_MNCLv4/logs/%x-%j.out
#SBATCH --error=/share/nas/cs-nas/zh932237/CMMLoc_MNCLv4/logs/%x-%j.err

# ---- Force ALL caches to node-local (avoid /home and /share/nas quotas) ----
CACHE_BASE=/share/nas/cs-nas/zh932237/hf_cache
mkdir -p "$CACHE_BASE"/{hf,hub,transformers,torch,xdg,tmp,pip}

export HF_HOME="$CACHE_BASE/hf"
export HF_HUB_CACHE="$CACHE_BASE/hub"
export TRANSFORMERS_CACHE="$CACHE_BASE/transformers"
export TORCH_HOME="$CACHE_BASE/torch"
export XDG_CACHE_HOME="$CACHE_BASE/xdg"
export TMPDIR="$CACHE_BASE/tmp"
export PIP_CACHE_DIR="$CACHE_BASE/pip"

# Show what will be used (very important for debugging)
echo "HF_HOME=$HF_HOME"
echo "HF_HUB_CACHE=$HF_HUB_CACHE"
echo "TRANSFORMERS_CACHE=$TRANSFORMERS_CACHE"
echo "XDG_CACHE_HOME=$XDG_CACHE_HOME"
# -------------------------------------------------------------------------





set -euo pipefail

cd /share/nas/cs-nas/zh932237/CMMLoc_MNCLv4
mkdir -p logs

# Activate your env (optional for hostname, but fine to keep)
source  /share/nas/cs-nas/zh932237/env_cmmloc_mnclv4/bin/activate

# Optional: show GPUs allocated
echo "Host: $(hostname)"
nvidia-smi -L

# Your requested command:
hostname

python -m training.fine --batch_size 64 --base_path ./data/k360_30-10_scG_pd10_pc4_spY_all --use_features class color position num --no_pc_augment --fixed_embedding --epochs 45 --learning_rate 0.0003 --lr_scheduler step --lr_step 15 --lr_gamma 0.5 --hungging_model t5-large --text_max_length 128 --offset_lambda 5 --num_mentioned 6 --pad_size 16 --cpus 0 --pointnet_path ./checkpoints/pointnet_acc0.86_lr1_p256.pth --prealign_pointnet_path ./checkpoints/k360_30-10_scG_pd10_pc4_spY_all/prealignv1_batch64_epoch20_ablation_study/best_pointnet.pth --prealign_color_path ./checkpoints/k360_30-10_scG_pd10_pc4_spY_all/prealignv1_batch64_epoch20_ablation_study/best_color_encoder.pth --prealign_mlp_path ./checkpoints/k360_30-10_scG_pd10_pc4_spY_all/prealignv1_batch64_epoch20_ablation_study/best_mlp.pth --folder_name finev1_batch64_epoch45_ablation_study